/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prog.burgurqueenapp;

import java.awt.Graphics;
import java.util.Objects;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DAW
 */
public class QueenApp extends javax.swing.JFrame {

    /**
     * Creates new form QueenApp
     */
    public QueenApp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
//    @Override
//    public void paint(Graphics g){
//        ImageIcon imagenfondo= new ImageIcon(Objects.requireNonNull(
//                this.getClass().getResource("/images/graficoBlank.jpg")));
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupHamburguesa = new javax.swing.ButtonGroup();
        btnGroupPan = new javax.swing.ButtonGroup();
        btnGroupPatatas = new javax.swing.ButtonGroup();
        btnGroupBebida = new javax.swing.ButtonGroup();
        btnGroupReparto = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHamburguesa = new javax.swing.JPanel();
        btnPollo = new javax.swing.JToggleButton();
        btnCerdo = new javax.swing.JToggleButton();
        btnTernera = new javax.swing.JToggleButton();
        btnVegana = new javax.swing.JToggleButton();
        btnNormal = new javax.swing.JToggleButton();
        btnIntegral = new javax.swing.JToggleButton();
        btnCenteno = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelComplementos = new javax.swing.JPanel();
        btnFritas = new javax.swing.JToggleButton();
        btnGajo = new javax.swing.JToggleButton();
        btnCaseras = new javax.swing.JToggleButton();
        btnCola = new javax.swing.JToggleButton();
        btnNaranja = new javax.swing.JToggleButton();
        btnLimon = new javax.swing.JToggleButton();
        btnNestea = new javax.swing.JToggleButton();
        btnAgua = new javax.swing.JToggleButton();
        btnCerveza = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelExtras = new javax.swing.JPanel();
        boxDoble = new javax.swing.JCheckBox();
        boxQueso = new javax.swing.JCheckBox();
        boxPatatas = new javax.swing.JCheckBox();
        spinnerKetchup = new javax.swing.JSpinner();
        spinnerBarbacoa = new javax.swing.JSpinner();
        spinnerThai = new javax.swing.JSpinner();
        spinnerMostaza = new javax.swing.JSpinner();
        labelKetchup = new javax.swing.JLabel();
        labelBarbacoa = new javax.swing.JLabel();
        labelMostaza = new javax.swing.JLabel();
        labelThai = new javax.swing.JLabel();
        jPanelCheckout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnDomicilio = new javax.swing.JToggleButton();
        btnRecogidaLocal = new javax.swing.JToggleButton();
        btnCheckout = new javax.swing.JButton();
        labelPrecioBase = new javax.swing.JLabel();
        labelExtrasMenus = new javax.swing.JLabel();
        labelExtras = new javax.swing.JLabel();
        labelSalsas = new javax.swing.JLabel();
        labelEnvioRecogida = new javax.swing.JLabel();
        labelTotalSinIVA = new javax.swing.JLabel();
        labelIVA = new javax.swing.JLabel();
        labelTotalPVP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(181, 255, 213));

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 204));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanelHamburguesa.setBackground(new java.awt.Color(255, 204, 255));
        jPanelHamburguesa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnGroupHamburguesa.add(btnPollo);
        btnPollo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPollo.setText("Pollo");

        btnGroupHamburguesa.add(btnCerdo);
        btnCerdo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCerdo.setText("Cerdo");

        btnGroupHamburguesa.add(btnTernera);
        btnTernera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTernera.setText("Ternera (+1€)");
        btnTernera.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnTerneraStateChanged(evt);
            }
        });

        btnGroupHamburguesa.add(btnVegana);
        btnVegana.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVegana.setText("Vegana (+1€)");
        btnVegana.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnVeganaStateChanged(evt);
            }
        });

        btnGroupPan.add(btnNormal);
        btnNormal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNormal.setText("Normal");

        btnGroupPan.add(btnIntegral);
        btnIntegral.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIntegral.setText("Integral");

        btnGroupPan.add(btnCenteno);
        btnCenteno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCenteno.setText("Centeno");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Elige la hamburguesa");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Elige el pan");

        javax.swing.GroupLayout jPanelHamburguesaLayout = new javax.swing.GroupLayout(jPanelHamburguesa);
        jPanelHamburguesa.setLayout(jPanelHamburguesaLayout);
        jPanelHamburguesaLayout.setHorizontalGroup(
            jPanelHamburguesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHamburguesaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelHamburguesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanelHamburguesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnTernera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPollo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVegana)))
                .addGap(79, 79, 79)
                .addGroup(jPanelHamburguesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHamburguesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIntegral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCenteno, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(65, 65, 65))
        );
        jPanelHamburguesaLayout.setVerticalGroup(
            jPanelHamburguesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHamburguesaLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addGroup(jPanelHamburguesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHamburguesaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(btnPollo)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerdo)
                        .addGap(18, 18, 18)
                        .addComponent(btnTernera))
                    .addGroup(jPanelHamburguesaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnNormal)
                        .addGap(18, 18, 18)
                        .addComponent(btnIntegral)
                        .addGap(18, 18, 18)
                        .addComponent(btnCenteno)))
                .addGap(18, 18, 18)
                .addComponent(btnVegana)
                .addGap(189, 189, 189))
        );

        jTabbedPane1.addTab("Hamburguesa", new javax.swing.ImageIcon(getClass().getResource("/images/iconBurgerSmall.png")), jPanelHamburguesa); // NOI18N

        jPanelComplementos.setBackground(new java.awt.Color(255, 204, 204));
        jPanelComplementos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnGroupPatatas.add(btnFritas);
        btnFritas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFritas.setText("Patatas fritas");

        btnGroupPatatas.add(btnGajo);
        btnGajo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGajo.setText("Patatas gajo");

        btnGroupPatatas.add(btnCaseras);
        btnCaseras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCaseras.setText("Patatas caseras (+1€)");

        btnGroupBebida.add(btnCola);
        btnCola.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCola.setText("Coca-cola");

        btnGroupBebida.add(btnNaranja);
        btnNaranja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNaranja.setText("Fanta naranja");

        btnGroupBebida.add(btnLimon);
        btnLimon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimon.setText("Fanta limón");

        btnGroupBebida.add(btnNestea);
        btnNestea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNestea.setText("Nestea");

        btnGroupBebida.add(btnAgua);
        btnAgua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgua.setText("Agua");

        btnGroupBebida.add(btnCerveza);
        btnCerveza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCerveza.setText("Cerveza");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Elige las patatas");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Elige la bebida");

        javax.swing.GroupLayout jPanelComplementosLayout = new javax.swing.GroupLayout(jPanelComplementos);
        jPanelComplementos.setLayout(jPanelComplementosLayout);
        jPanelComplementosLayout.setHorizontalGroup(
            jPanelComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComplementosLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addGroup(jPanelComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnCaseras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFritas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanelComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanelComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNaranja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCola, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNestea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerveza, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
        );
        jPanelComplementosLayout.setVerticalGroup(
            jPanelComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComplementosLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jPanelComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(jPanelComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFritas)
                        .addComponent(btnCola))
                    .addGroup(jPanelComplementosLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanelComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGajo)
                            .addComponent(btnNaranja))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelComplementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCaseras)
                            .addComponent(btnLimon))
                        .addGap(18, 18, 18)
                        .addComponent(btnNestea)))
                .addGap(18, 18, 18)
                .addComponent(btnAgua)
                .addGap(18, 18, 18)
                .addComponent(btnCerveza)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Complementos", new javax.swing.ImageIcon(getClass().getResource("/images/iconPapasSmall.png")), jPanelComplementos); // NOI18N

        jPanelExtras.setBackground(new java.awt.Color(255, 221, 188));
        jPanelExtras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        boxDoble.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxDoble.setText("Hazla doble (+2€)");

        boxQueso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxQueso.setText("Extra de queso (+0.50€)");

        boxPatatas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxPatatas.setText("Extra de patatas (+1€)");

        spinnerKetchup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinnerKetchup.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        spinnerBarbacoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinnerBarbacoa.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        spinnerThai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinnerThai.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        spinnerMostaza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinnerMostaza.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        labelKetchup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKetchup.setText("Ketchup");

        labelBarbacoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelBarbacoa.setText("Barbacoa");

        labelMostaza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMostaza.setText("Mostaza");

        labelThai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelThai.setText("Thai");

        javax.swing.GroupLayout jPanelExtrasLayout = new javax.swing.GroupLayout(jPanelExtras);
        jPanelExtras.setLayout(jPanelExtrasLayout);
        jPanelExtrasLayout.setHorizontalGroup(
            jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExtrasLayout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxPatatas)
                    .addComponent(boxQueso)
                    .addComponent(boxDoble)
                    .addGroup(jPanelExtrasLayout.createSequentialGroup()
                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelExtrasLayout.createSequentialGroup()
                                .addComponent(spinnerKetchup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelKetchup)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spinnerBarbacoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelExtrasLayout.createSequentialGroup()
                                .addComponent(spinnerMostaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelMostaza)
                                .addGap(54, 54, 54)
                                .addComponent(spinnerThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBarbacoa)
                            .addComponent(labelThai))))
                .addGap(67, 67, 67))
        );
        jPanelExtrasLayout.setVerticalGroup(
            jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExtrasLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(boxDoble)
                .addGap(18, 18, 18)
                .addComponent(boxQueso)
                .addGap(18, 18, 18)
                .addComponent(boxPatatas)
                .addGap(53, 53, 53)
                .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerKetchup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerBarbacoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKetchup)
                    .addComponent(labelBarbacoa))
                .addGap(36, 36, 36)
                .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerMostaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMostaza)
                    .addComponent(labelThai))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Extras           ", new javax.swing.ImageIcon(getClass().getResource("/images/iconSalsasSmall.png")), jPanelExtras); // NOI18N

        jPanelCheckout.setBackground(new java.awt.Color(255, 255, 204));
        jPanelCheckout.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelCheckoutComponentShown(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Menú básico");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Extras menú");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Extras opcionales");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Salsas");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Envío o recogida");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Total sin IVA");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("IVA (21%)");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("PVP");

        btnGroupReparto.add(btnDomicilio);
        btnDomicilio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDomicilio.setText("A domicilio");

        btnGroupReparto.add(btnRecogidaLocal);
        btnRecogidaLocal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRecogidaLocal.setText("Recogida en local");

        btnCheckout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCheckout.setText("Hacer pedido");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        labelPrecioBase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPrecioBase.setText("8 €");

        labelExtrasMenus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelExtrasMenus.setText("0 €");

        labelExtras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelExtras.setText("0 €");

        labelSalsas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSalsas.setText("0 €");

        labelEnvioRecogida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEnvioRecogida.setText("0 €");

        labelTotalSinIVA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTotalSinIVA.setText("8 €");

        labelIVA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelIVA.setText("0 €");

        labelTotalPVP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTotalPVP.setText("0 €");

        javax.swing.GroupLayout jPanelCheckoutLayout = new javax.swing.GroupLayout(jPanelCheckout);
        jPanelCheckout.setLayout(jPanelCheckoutLayout);
        jPanelCheckoutLayout.setHorizontalGroup(
            jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btnCheckout))
                    .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(btnDomicilio))
                        .addGap(65, 65, 65)
                        .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelExtrasMenus)
                                .addComponent(labelPrecioBase)
                                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelExtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelSalsas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelEnvioRecogida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelTotalSinIVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelIVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelTotalPVP)))
                            .addComponent(btnRecogidaLocal))))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanelCheckoutLayout.setVerticalGroup(
            jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDomicilio)
                    .addComponent(btnRecogidaLocal))
                .addGap(71, 71, 71)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelPrecioBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelExtrasMenus))
                .addGap(10, 10, 10)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelExtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelSalsas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labelEnvioRecogida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelTotalSinIVA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelIVA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(labelTotalPVP))
                .addGap(62, 62, 62)
                .addComponent(btnCheckout)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Check out", jPanelCheckout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*DECLARACIÓN DE VARIABLES ESTÁTICAS*/
    public static double totalSinIVA;
    public static double IVA;
    public static double totalConIVA;
    
    public static double extraHamburguesa;
    public static double extraPatatasCaseras;
    public static double extraHamburguesaDoble;
    public static double extraQueso;
    public static double extraPatatas;
    public static int extraSalsas;
    
    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:
        if(btnGroupHamburguesa.getSelection()==null){
            JOptionPane.showMessageDialog(this, "¡No has seleccionado el tipo de hamburguesa!", "Pedido incompleto", JOptionPane.WARNING_MESSAGE);
        }else 
        if(btnGroupPan.getSelection()==null){
            JOptionPane.showMessageDialog(this, "¡No has seleccionado el tipo de pan!", "Pedido incompleto", JOptionPane.WARNING_MESSAGE);
        }else
        if(btnGroupPatatas.getSelection()==null){
            JOptionPane.showMessageDialog(this, "¡No has seleccionado el tipo de patatas!", "Pedido incompleto", JOptionPane.WARNING_MESSAGE);
        }else
        if(btnGroupBebida.getSelection()==null){
            JOptionPane.showMessageDialog(this, "¡No has seleccionado una bebida!", "Pedido incompleto", JOptionPane.WARNING_MESSAGE);
        }else
        if(btnGroupReparto.getSelection()==null){
            JOptionPane.showMessageDialog(this, "Por favor, elige primero el tipo de pedido (a domicilio o recogida en local)", "Pedido incompleto", JOptionPane.WARNING_MESSAGE);
        }else{
            //Esto es que está todo elegido
            JOptionPane.showMessageDialog(this, "¡Oído cocina! Tu pedido está en marcha", "Pedido realizado", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnTerneraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnTerneraStateChanged
        // TODO add your handling code here:
        if(btnTernera.isSelected()){
            extraHamburguesa=1;
        }else{
            extraHamburguesa=0;
        }
    }//GEN-LAST:event_btnTerneraStateChanged

    private void btnVeganaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnVeganaStateChanged
        // TODO add your handling code here:
        if(btnVegana.isSelected()){
            extraHamburguesa=1;
        }else{
            extraHamburguesa=0;
        }
    }//GEN-LAST:event_btnVeganaStateChanged

    private void jPanelCheckoutComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelCheckoutComponentShown
        // TODO add your handling code here:
        // REFRESCA LISTA DE CHECKOUT AL MOSTRAR TAB DE CHECKOUT
        
        totalSinIVA=8+extraHamburguesa+extraPatatasCaseras+extraHamburguesaDoble+extraQueso+extraPatatas+extraSalsas;
        labelTotalSinIVA.setText(totalSinIVA+" €");
        
        labelExtrasMenus.setText((extraHamburguesa+extraPatatasCaseras)+" €");
        
        labelExtras.setText((extraHamburguesaDoble+extraQueso+extraPatatas)+" €");
        
        labelSalsas.setText((extraSalsas*0.50)+" €");
        
        IVA=totalSinIVA*0.21;
        labelIVA.setText(IVA+" €");
        
        totalConIVA=totalSinIVA+IVA;
        labelTotalPVP.setText(totalConIVA+" €");
        
        //System.out.println("hola component shown");
    }//GEN-LAST:event_jPanelCheckoutComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueenApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueenApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueenApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueenApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //this.setLocationRelativeTo(null);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QueenApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxDoble;
    private javax.swing.JCheckBox boxPatatas;
    private javax.swing.JCheckBox boxQueso;
    private javax.swing.JToggleButton btnAgua;
    private javax.swing.JToggleButton btnCaseras;
    private javax.swing.JToggleButton btnCenteno;
    private javax.swing.JToggleButton btnCerdo;
    private javax.swing.JToggleButton btnCerveza;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JToggleButton btnCola;
    private javax.swing.JToggleButton btnDomicilio;
    private javax.swing.JToggleButton btnFritas;
    private javax.swing.JToggleButton btnGajo;
    private javax.swing.ButtonGroup btnGroupBebida;
    private javax.swing.ButtonGroup btnGroupHamburguesa;
    private javax.swing.ButtonGroup btnGroupPan;
    private javax.swing.ButtonGroup btnGroupPatatas;
    private javax.swing.ButtonGroup btnGroupReparto;
    private javax.swing.JToggleButton btnIntegral;
    private javax.swing.JToggleButton btnLimon;
    private javax.swing.JToggleButton btnNaranja;
    private javax.swing.JToggleButton btnNestea;
    private javax.swing.JToggleButton btnNormal;
    private javax.swing.JToggleButton btnPollo;
    private javax.swing.JToggleButton btnRecogidaLocal;
    private javax.swing.JToggleButton btnTernera;
    private javax.swing.JToggleButton btnVegana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCheckout;
    private javax.swing.JPanel jPanelComplementos;
    private javax.swing.JPanel jPanelExtras;
    private javax.swing.JPanel jPanelHamburguesa;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelBarbacoa;
    private javax.swing.JLabel labelEnvioRecogida;
    private javax.swing.JLabel labelExtras;
    private javax.swing.JLabel labelExtrasMenus;
    private javax.swing.JLabel labelIVA;
    private javax.swing.JLabel labelKetchup;
    private javax.swing.JLabel labelMostaza;
    private javax.swing.JLabel labelPrecioBase;
    private javax.swing.JLabel labelSalsas;
    private javax.swing.JLabel labelThai;
    private javax.swing.JLabel labelTotalPVP;
    private javax.swing.JLabel labelTotalSinIVA;
    private javax.swing.JSpinner spinnerBarbacoa;
    private javax.swing.JSpinner spinnerKetchup;
    private javax.swing.JSpinner spinnerMostaza;
    private javax.swing.JSpinner spinnerThai;
    // End of variables declaration//GEN-END:variables
}
